id: I4CB69923
legacy_id: P5839F145
ocr_import_info:
  bdrc_scan_id: W1KG13817
  source: bdrc
  ocr_info:
    timestamp: '2022-03-28T05:30:13'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T06:46:40.701664+00:00'
last_modified: 2022-08-31 14:47:02.569055
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG13817
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG13817
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བརྡ་དག་སྙན་ངག་སོགས་ཐ་སྙད་རིག་གནས་ཀྱི་གཞུང་གཅེས་བཏུས།
statistics:
  ocr_word_mean_confidence_index: 0.9744306661839247
  ocr_word_median_confidence_index: 0.99
quality: null
bases:
  I1KG15834:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15834
      total_pages: 404
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15834.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9744306661839247
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
